apiVersion: apps/v1
kind: Deployment
metadata:
   name: position-tracker
   labels:
      apps: position-tracker
spec:
   replicas: 1
   selector:
          matchLabels:
                  apps: position-tracker
   template:
       metadata:
          labels:
             apps: position-tracker
       spec:
         containers:
              - name: position-tracker
                image: richardchesterwood/k8s-fleetman-position-tracker:release1
                env:
                - name: SPRING_PROFILES_ACTIVE
                  value: local-microservice
                ports:
                - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
     name: fleetman-position-tracker
spec:
  selector:
     apps: position-tracker
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
