apiVersion: apps/v1
kind: Deployment
metadata:
    name: queue-deployment
    labels:
       apps: queue

spec:
  replicas: 1
  selector:
      matchLabels:
        apps: queue

  template:
       metadata:
           labels:
               apps: queue
       spec:
         containers:
            - name: http
              image: richardchesterwood/k8s-fleetman-queue:release1
              ports:
               - containerPort: 8161
                 containerPort: 61616






---

apiVersion: v1
kind: Service
metadata:
    name: fleetman-queue

spec:
  selector:
     apps: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30120

    - name: internal
      port: 61616

  type: NodePort
